pipeline:
  docs:
    image: python:3.9-alpine
    pull: true
    commands:
      - apk add --no-cache --virtual .build-deps gcc musl-dev &&
        apk add --no-cache git bash build-base libffi-dev openssl-dev bzip2-dev zlib-dev readline-dev sqlite-dev curl && rm -rf /var/cache/apk/*
      - python -m pip install poetry
      - poetry run pip install -r requirements-dev.txt
      - export ALIAS='latest'
      - VERSION=$$(poetry version -s); poetry run mike deploy $${VERSION} $${ALIAS} || poetry run mike deploy --push --update-aliases $${VERSION} $${ALIAS}
    when:
      branch: master
  docs-develop:
    image: python:3.9-alpine
    pull: true
    commands:
      - apk add --no-cache --virtual .build-deps gcc musl-dev &&
        apk add --no-cache git bash build-base libffi-dev openssl-dev bzip2-dev zlib-dev readline-dev sqlite-dev curl && rm -rf /var/cache/apk/*
      - python -m pip install poetry
      - poetry run pip install -r requirements-dev.txt
      - export ALIAS='develop'
      - export VERSION=`poetry version -s`
      # Specify git repo credentials to push back to the gh-pages branch
      - git config credential.$(git remote get-url origin).username ${GIT_USER}
      - git config credential.$(git remote get-url origin).password ${GIT_PASSWORD}
      - git config user.name ${GIT_USER}
      - git config user.email ${GIT_EMAIL}
      # Build and deploy
      - poetry run mike deploy --push $${VERSION} $${ALIAS}
    when:
      branch: develop
    secrets: [GIT_USER, GIT_PASSWORD, GIT_EMAIL]
branches: [master, develop]
