pipeline:
  docs:
    image: python:3.9-alpine
    pull: true
    commands:
      # Setup packages
      - apk add --no-cache --virtual .build-deps gcc musl-dev &&
        apk add --no-cache git bash build-base libffi-dev openssl-dev bzip2-dev zlib-dev readline-dev sqlite-dev curl && rm -rf /var/cache/apk/*
      - python -m pip install --upgrade pip poetry
      - poetry run pip install -r requirements-dev.txt
      # Determine alias tag and version number
      - export ALIAS=`if [ ${CI_COMMIT_BRANCH} = master ]; then echo latest; else echo develop; fi`
      - export VERSION=`poetry version -s`
      # Specify git repo credentials to push back to the gh-pages branch
      - export REPO=`git remote get-url origin`
      - git config --global credential.helper store
      # - git config --global credential.username $${GIT_USER}
      # - git config --global credential.password $${GIT_PASSWORD}
      - git config --global user.name $${GIT_USER}
      - git config --global user.password $${GIT_PASSWORD}
      - git config --global user.email $${GIT_EMAIL}
      - cat .git/config
      # Build and deploy
      - poetry run mike deploy --push $${VERSION} $${ALIAS}
    secrets: [GIT_USER, GIT_PASSWORD, GIT_EMAIL]
branches: [master, develop]
