pipeline:
  docs:
    image: python:3.9-alpine
    pull: true
    commands:
      # Setup packages
      - apk add --no-cache --virtual .build-deps gcc musl-dev &&
        apk add --no-cache git bash build-base libffi-dev openssl-dev bzip2-dev zlib-dev readline-dev sqlite-dev curl && rm -rf /var/cache/apk/*
      - python -m pip install --upgrade pip poetry
      - poetry run pip install -r requirements-dev.txt
      # Determine alias tag and version number
      - export ALIAS=`if [ ${CI_COMMIT_BRANCH} = master ]; then echo latest; else echo ${CI_COMMIT_BRANCH}; fi`
      - export VERSION=`poetry version -s`
      # Specify git repo credentials to push back to the gh-pages branch
      - export REPO=`git remote get-url origin`
      - export REMOTE=`echo 'https://'$${GIT_USER}':'$${GIT_PASSWORD}'@git.jamesveitch.xyz/'$${CI_REPO}`
      - git config --global user.name $${GIT_USER}
      - git config --global user.password $${GIT_PASSWORD}
      - git config --global user.email $${GIT_EMAIL}
      # add a new remote called pages with the new creds
      # - git remote add pages $${REMOTE}
      # overwrite the remote with the new creds
      - git remote set-url origin $${REMOTE}
      - git branch --set-upstream-to=origin/$${CI_COMMIT_BRANCH} master
      - git pull
      - git checkout gh-pages
      - git checkout master
      # Build and deploy as ci-bot user and forcing use of new `pages` remote
      # - poetry run mike deploy --remote pages --push --update-aliases $${VERSION} $${ALIAS}
      # Build and deploy as ci-bot user
      - poetry run mike deploy --push --update-aliases $${VERSION} $${ALIAS}
    secrets: [GIT_USER, GIT_PASSWORD, GIT_EMAIL]
branches: [master, develop]
