# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

recorder:
  db_url: mysql://homeassistant:4546842aa4db7a799d74a761597c556b@core-mariadb:3306/homeassistant?charset=utf8
  purge_keep_days: 365
  exclude:
    entities:
      - sun.sun

# Text to speech
tts:
  - platform: google_translate

notify:
# not included

# Includes

# Templates / modbus conf
modbus: !include modbus.yaml
# Includes all Templates / Sensors in folder sensor
sensor: !include_dir_merge_list sensor/
