# Variables
substitutions:
  devicename: mancave-mains-node
  friendly_devicename: "Mancave Desk Mains PDU"

# Config
esphome:
  name: ${devicename}
  platform: ESP8266
  board: esp8285

# Enable logging
logger:

# Enable Home Assistant API
api:
  # password: "f8f42ee743645df28a54f5da249d1bbc5544e29fd06e80b0ed033842c852201a"

ota:
  # password: "f8f42ee743645df28a54f5da249d1bbc5544e29fd06e80b0ed033842c852201a"

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${devicename} Hotspot"
    password: !secret node_ap_password

captive_portal:

# Sonoff R2 functionality
binary_sensor:
  - platform: status
    name: "${friendly_devicename}: Status"
  - platform: gpio
    name: "Main Button"
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: true
    on_press:
      - switch.toggle: relay

switch:
  # Relay itself
  - platform: gpio
    name: "${friendly_devicename}: Relay"
    pin: GPIO12
    id: relay

# Measuring and debugging
web_server:
  port: 80

sensor:
  - platform: wifi_signal
    name: "${friendly_devicename}: Wifi Signal Strength"
    update_interval: 60s
  - platform: uptime
    name: "${friendly_devicename}: Uptime"

text_sensor:
  # Reports the ESPHome Version with compile date
  - platform: version
    name: "${friendly_devicename}: ESPHome Version"
  # Reports detailed wifi info
  - platform: wifi_info
    ip_address:
      name: "${friendly_devicename}: IP"
      icon: "mdi:ip-outline"
    ssid:
      name: "${friendly_devicename}: SSID"
      icon: "mdi:wifi-settings"
    bssid:
      name: "${friendly_devicename}: BSSID"
      icon: "mdi:wifi-settings"
    mac_address:
      name: "${friendly_devicename}: MAC"
      icon: "mdi:network-outline"
    scan_results:
      name: "${friendly_devicename}: Wifi Scan"
      icon: "mdi:wifi-refresh"
      disabled_by_default: true
